In [18]:
!pip install torch 

In [20]:
import torch

In [30]:
print(torch.__version__)

2.7.1+cpu


In [317]:
import random

In [319]:
scalar = torch.tensor(5)
scalar

tensor(5)

In [321]:
scalar.ndim

0

In [323]:
scalar.item()

5

In [325]:
vector=torch.tensor([5,5])
vector

tensor([5, 5])

In [327]:
vector.ndim

1

In [329]:
vector.shape

torch.Size([2])

In [331]:
Matrix=torch.tensor([[1,2],[3,4]])
Matrix

tensor([[1, 2],
        [3, 4]])

In [333]:
Matrix.ndim

2

In [335]:
Matrix.shape

torch.Size([2, 2])

In [337]:
x = torch.tensor([[[1, 2],
                        [3, 4],
                        [5, 6]]])
x

tensor([[[1, 2],
         [3, 4],
         [5, 6]]])

In [339]:
x.ndim

3

In [341]:
x.shape

torch.Size([1, 3, 2])

In [343]:
x[0][2]

tensor([5, 6])

# Random Tensor

In [346]:
random_tensor = torch.rand(size=(4,6))
random_tensor

tensor([[0.9020, 0.6097, 0.3405, 0.4795, 0.0642, 0.0278],
        [0.1513, 0.0163, 0.8290, 0.3250, 0.3650, 0.0694],
        [0.5828, 0.4250, 0.1596, 0.8206, 0.9215, 0.1436],
        [0.7833, 0.4188, 0.4953, 0.7128, 0.4088, 0.9248]])

In [348]:
random_tensor.dtype

torch.float32

In [350]:
random_tensor.ndim

2

In [352]:
random_tensor.shape

torch.Size([4, 6])

In [354]:
random_tensor_0 = torch.rand(size=(3,4,6))
random_tensor_0

tensor([[[0.8076, 0.1754, 0.1957, 0.0046, 0.6601, 0.1239],
         [0.0809, 0.1795, 0.0057, 0.0929, 0.9460, 0.7793],
         [0.9430, 0.2575, 0.2949, 0.3246, 0.5098, 0.1411],
         [0.5733, 0.1796, 0.5790, 0.9580, 0.5844, 0.8647]],

        [[0.1439, 0.4294, 0.1913, 0.4445, 0.3011, 0.2161],
         [0.0170, 0.3146, 0.5670, 0.4120, 0.0343, 0.8756],
         [0.8707, 0.1985, 0.5508, 0.8320, 0.0252, 0.0582],
         [0.7774, 0.4901, 0.6592, 0.2921, 0.5907, 0.8316]],

        [[0.3777, 0.3385, 0.0239, 0.4228, 0.8168, 0.0275],
         [0.4614, 0.8645, 0.3573, 0.3153, 0.3492, 0.2974],
         [0.5598, 0.0186, 0.6911, 0.3737, 0.4363, 0.4663],
         [0.7793, 0.1894, 0.0450, 0.1383, 0.1332, 0.2566]]])

In [356]:
random_tensor_0.ndim, random_tensor_0.shape

(3, torch.Size([3, 4, 6]))

In [358]:
zeros = torch.zeros(size = (4,6))
zeros

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [360]:
ones = torch.ones(size = (4,6))
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

# Creating a range of tensors

In [363]:
a = torch.arange(0,10)
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [365]:
b = torch.zeros_like(a)
b

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Operations

In [368]:
t = torch.tensor([1,2,3])
t+10

tensor([11, 12, 13])

In [370]:
t*10

tensor([10, 20, 30])

In [372]:
t*t

tensor([1, 4, 9])

In [374]:
t**2

tensor([1, 4, 9])

In [376]:
a = torch.tensor([1.0, 2.0])
b = torch.tensor([3.0, 4.0])

print("Elemantwise addition of a and b: \n", a+b)

print('matrix multiplication of a and b:\n ', torch.matmul(a.view(2,1), b.view(1,2)))

Elemantwise addition of a and b: 
 tensor([4., 6.])
matrix multiplication of a and b:
  tensor([[3., 4.],
        [6., 8.]])


# Reshaping, Resizing, Transposing

In [379]:
t = torch.tensor([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12]])

print("Reshaping: \n", t.reshape(6,2))

Reshaping: 
 tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]])


In [381]:
print("Resizing: \n", t.view(2,6))

Resizing: 
 tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])


In [383]:
print("Transposing: \n", t.transpose(0,1))

Transposing: 
 tensor([[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]])


# Seed in pytorch

In [386]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.8949, 0.1132, 0.2061, 0.0924],
        [0.2488, 0.4860, 0.1951, 0.5053],
        [0.6690, 0.4149, 0.7157, 0.6147]])

Tensor B:
tensor([[0.9830, 0.4745, 0.9334, 0.8742],
        [0.7390, 0.7830, 0.1651, 0.1651],
        [0.7135, 0.6816, 0.9512, 0.4349]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [388]:
random_seed=42
torch.manual_seed(seed=random_seed)
random_tensor_C = torch.rand(3, 4)

torch.random.manual_seed(seed=random_seed) 
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

# Building neural networks in pytoch

In [263]:
import torch
import torch.nn as nn # To define neural network layers and models
import torch.optim as optim # Optimizer for training(like SGD, Adam etc)

In [273]:
class NeuralNetwork(nn.Module):
  def __init__(self):
    super(NeuralNetwork, self).__init__()
    self.fc1 = nn.Linear(10,16) # first layer
    self.fc2 = nn.Linear(16,8)  # 2nd layer
    self.fc3 = nn.Linear(8,1)   # 3rd layer

  def forward(self, x):
    x = torch.relu(self.fc1(x))
    x = torch.relu(self.fc2(x))
    x = torch.sigmoid(self.fc3(x))
    return x

#Model setup
model = NeuralNetwork()
print("Model: \n", model)

#Loss and Optimizer
criterion = nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(),lr = 0.01)

inputs = torch.randn((100,10))
targets = torch.randint(0,2,(100,1)).float()
epochs = 20

for epoch in range(epochs):
  optimizer.zero_grad()   #clear old gradients
  outputs = model(inputs)
  loss = criterion(outputs, targets)  # compute loss between prediction and target
  loss.backward()   # Backward pass: Computes gradient of loss w.r.t. weight.
  optimizer.step()  # Update weight to reduce the loss

  if (epoch+1) % 5 == 0:
    print(f"Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}")

Model: 
 NeuralNetwork(
  (fc1): Linear(in_features=10, out_features=16, bias=True)
  (fc2): Linear(in_features=16, out_features=8, bias=True)
  (fc3): Linear(in_features=8, out_features=1, bias=True)
)
Epoch [5/20], Loss: 0.6796
Epoch [10/20], Loss: 0.6623
Epoch [15/20], Loss: 0.6313
Epoch [20/20], Loss: 0.5885


In [269]:
class SimpleNet(nn.Module):
  def __init__(self):
    super(SimpleNet, self).__init__()
    self.weight = nn.Parameter(torch.randn(1, requires_grad = True))

  def forward(self, x):
    return x * self.weight

model = SimpleNet()
print("Initial model parameters: ", list(model.parameters()))

criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

input_tensor = torch.tensor([2.0])
target_tensor = torch.tensor([4.0])

for epoch in range(100):
  optimizer.zero_grad 
  output = model(input_tensor)
  loss = criterion(output, target_tensor) 
  loss.backward() 
  optimizer.step()  

  if epoch % 10 == 0:
    print(f"Epoch {epoch}, Loss: {loss.item()}, weght: {model.weight.item()}")

print("Final Model Parameters: ", list(model.parameters()))


Initial model parameters:  [Parameter containing:
tensor([-1.2490], requires_grad=True)]
Epoch 0, Loss: 42.22442626953125, weght: -0.9890949726104736
Epoch 10, Loss: 41.96862030029297, weght: 5.257591724395752
Epoch 20, Loss: 34.40822219848633, weght: -1.2280254364013672
Epoch 30, Loss: 22.246994018554688, weght: 4.903101444244385
Epoch 40, Loss: 9.834027290344238, weght: -0.31254899501800537
Epoch 50, Loss: 1.6084543466567993, weght: 3.510403633117676
Epoch 60, Loss: 0.5118977427482605, weght: 1.4299404621124268
Epoch 70, Loss: 6.9365081787109375, weght: 1.5775556564331055
Epoch 80, Loss: 18.5847110748291, weght: 3.3762948513031006
Epoch 90, Loss: 31.290882110595703, weght: -0.2042173147201538
Final Model Parameters:  [Parameter containing:
tensor([5.1824], requires_grad=True)]
